apiVersion: v1
kind: Service
metadata:
  name: srv-netology
spec:
  selector:
    app: netology
  ports:
    - name: nginx
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 1180
      targetPort: 1180
    - name: https-multitool
      protocol: TCP
      port: 11443
      targetPort: 11443
