apiVersion: v1
kind: Service
metadata:
  name: srv-node-port
spec:
  selector:
    app: netology
  ports:
  - name: nginx
    protocol: TCP
    nodePort: 30080
    port: 80
  - name: http-multitool
    protocol: TCP
    nodePort: 30880
    port: 8080
  type: NodePort
