apiVersion: v1
kind: Service
metadata:
  name: srv-netology
spec:
  selector:
    app: netology
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: http-multitool
      protocol: TCP
      port: 9002
      targetPort: 8080
